# Zathura colors — generated by Omarchy from colors.toml. Do not edit.
# Template: zathura/omarchy-theme.tpl, linked as ~/.config/omarchy/themed/zathura.tpl
# Included by ~/.config/zathura/zathurarc. The glass comes from the
# Hyprland opacity rule in hypr/looknfeel.lua, not from these colors.

set notification-error-bg       "{{ red }}"
set notification-error-fg       "{{ background }}"
set notification-warning-bg     "{{ yellow }}"
set notification-warning-fg     "{{ background }}"
set notification-bg             "{{ background }}"
set notification-fg             "{{ foreground }}"

set completion-bg               "{{ lighter_background }}"
set completion-fg               "{{ foreground }}"
set completion-group-bg         "{{ lighter_background }}"
set completion-group-fg         "{{ accent }}"
set completion-highlight-bg     "{{ accent }}"
set completion-highlight-fg     "{{ background }}"

set index-bg                    "{{ background }}"
set index-fg                    "{{ foreground }}"
set index-active-bg             "{{ selection_background }}"
set index-active-fg             "{{ selection_foreground }}"

set inputbar-bg                 "{{ lighter_background }}"
set inputbar-fg                 "{{ foreground }}"
set statusbar-bg                "{{ lighter_background }}"
set statusbar-fg                "{{ foreground }}"

set highlight-color             "{{ selection_background }}"
set highlight-active-color      "{{ accent }}"
set default-bg                  "{{ background }}"
set default-fg                  "{{ foreground }}"
set recolor-lightcolor          "{{ background }}"
set recolor-darkcolor           "{{ foreground }}"
