-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all
-- Generated by hyprmoncfg; GDK_SCALE stays 1x for 1080p + ultrawide 1440p.

hl.env("GDK_SCALE", "1")

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@60.00",
	position = "auto",
	scale = 1,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})
