$activeBorderColor = rgba(FFC799ee)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = rgba(57575faa)
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = rgba(57575faa)
}
